### ISSUE TITLE
RFC: source repo branches, tags and docker image tags

### ISSUE THREAD

**Issue by jcfr** [thewtex/docker-centos-build#10]
I suggest 

(1) we adopt the following tagging convention for docker image:
* `centosX-latest`
* `centosX-YYYYMMDD`    

(2) tag source repository using tag like these ones:

* `centosX-YYYYMMDD`

I also suggest we rename (or copy) the existing tag `v1.0.0` to `centos5-20151210`

(2) we option to manage the sources of the different images:

 (a) create maintenance branch for each version of centos we support: `centos5`, `centos6` and `centos7`

and also a branch named `welcome` with a README.md explaining what is available in this repo.

 (b) add subdirectory like `centos5`, `centos6`, `centos7` ....  Since dockerhub support specifying location of dockerfile, this should work well too: https://docs.docker.com/docker-hub/builds/#create-an-automated-build

**Comment by fedorov** [comment]
(1) it would be great, but is it possible to do this automatically?

(2) I would prefer to organize dockerfiles in directories instead of branches. Fewer things to remember!

**Comment by jcfr** [comment]
Thanks for the feedback.  We will have on directory for each image.

Closing. This will be address by #11

**Comment by jcfr** [comment]
@fedorov @thewtex Et voila, three lightweight images based on centos 5, 6 and 7 are now available for download.

They all include latest git, cmake, ninja, python 3.5 and call download files using TLS 1.2 thanks to an up-to-date curl executable.

**Comment by thewtex** [comment]
This is great, @jcfr , thanks!
